CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]
c_compiler:                    # [osx]
  - clang_rtti                 # [osx]
cxx_compiler:                  # [osx]
  - clangxx_rtti               # [osx]
c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]