macos_min_version:             # [osx]
  - 10.9                       # [osx]
macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]
c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]